# Generated by Django 6.0.2 on 2026-03-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Oddiy foydalanuvchi'), ('owner', "Do'kon egasi"), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
