services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: topnarx
      POSTGRES_USER: topnarx
      POSTGRES_PASSWORD: topnarx_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - appnet
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U topnarx"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - appnet
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: ./backend
    container_name: topnarxuz-web
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DEBUG: "True"
      SECRET_KEY: "super-secret-key-dev-change-in-production"
      DB_NAME: topnarx
      DB_USER: topnarx
      DB_PASSWORD: topnarx_pass
      DB_HOST: db
      DB_PORT: "5432"
      REDIS_URL: "redis://redis:6379/0"
      ALLOWED_HOSTS: "localhost,127.0.0.1,*"
      CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/staticfiles:/app/staticfiles
      - ./backend/media:/app/media
    networks:
      - appnet
    command: python manage.py runserver 0.0.0.0:8000

  celery_worker:
    build: ./backend
    container_name: topnarxuz-celery-worker
    command: celery -A config worker -l info --pool=solo
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DEBUG: "True"
      SECRET_KEY: "super-secret-key-dev-change-in-production"
      DB_NAME: topnarx
      DB_USER: topnarx
      DB_PASSWORD: topnarx_pass
      DB_HOST: db
      DB_PORT: "5432"
      REDIS_URL: "redis://redis:6379/0"
      ALLOWED_HOSTS: "*"
    volumes:
      - ./backend:/app
      - ./backend/staticfiles:/app/staticfiles
      - ./backend/media:/app/media
    networks:
      - appnet

  celery_beat:
    build: ./backend
    container_name: topnarxuz-celery-beat
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DEBUG: "True"
      SECRET_KEY: "super-secret-key-dev-change-in-production"
      DB_NAME: topnarx
      DB_USER: topnarx
      DB_PASSWORD: topnarx_pass
      DB_HOST: db
      DB_PORT: "5432"
      REDIS_URL: "redis://redis:6379/0"
      ALLOWED_HOSTS: "*"
    volumes:
      - ./backend:/app
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet:
    driver: bridge