# Generated by Django 6.0.2 on 2026-02-08 16:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_amount', models.IntegerField()),
                ('currency', models.CharField(default='UZS', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('source_type', models.CharField(choices=[('admin', 'Admin'), ('restaurant', 'Restaurant'), ('community', 'Community')], default='admin', max_length=20)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='places.restaurant')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='menu.menuitemvariant')),
            ],
            options={
                'indexes': [models.Index(fields=['restaurant'], name='pricing_men_restaur_afa74f_idx'), models.Index(fields=['variant'], name='pricing_men_variant_45aa4b_idx'), models.Index(fields=['price_amount'], name='pricing_men_price_a_8d35d9_idx')],
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'variant'), name='uniq_restaurant_variant_price')],
            },
        ),
    ]
