# Generated by Django 6.0.2 on 2026-03-11 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_feature_restaurantfeature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,null=True,
            related_name='restaurants', to=settings.AUTH_USER_MODEL, verbose_name='Egasi'),
            preserve_default=False,
        ),
    ]
