# Generated by Django 5.1 on 2026-06-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='default_unit',
            field=models.CharField(choices=[('ml', 'ml'), ('dona', 'dona'), ('g', 'g'), ('pcs', 'pcs')], default='pcs', max_length=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='menuitemvariant',
            name='size_unit',
            field=models.CharField(choices=[('ml', 'ml'), ('dona', 'dona'), ('g', 'g'), ('pcs', 'pcs')], max_length=10),
        ),
    ]
